"""local/chapter_list.py — CHK12 章节完整性预期表（自动生成）。"""
EXPECTED_CHAPTERS = [
    (1, 'TTLU-ch01', 'Twenty Thousand Leagues Under the Sea — CHAPTER 1'),
    (2, 'TTLU-ch02', 'Twenty Thousand Leagues Under the Sea — CHAPTER 2'),
    (3, 'TTLU-ch03', 'Twenty Thousand Leagues Under the Sea — CHAPTER 3'),
    (4, 'TTLU-ch04', 'Twenty Thousand Leagues Under the Sea — CHAPTER 4'),
    (5, 'TTLU-ch05', 'Twenty Thousand Leagues Under the Sea — CHAPTER 5'),
    (6, 'TTLU-ch06', 'Twenty Thousand Leagues Under the Sea — CHAPTER 6'),
    (7, 'TTLU-ch07', 'Twenty Thousand Leagues Under the Sea — CHAPTER 7'),
    (8, 'TTLU-ch08', 'Twenty Thousand Leagues Under the Sea — CHAPTER 8'),
    (9, 'TTLU-ch09', 'Twenty Thousand Leagues Under the Sea — CHAPTER 9'),
    (10, 'TTLU-ch10', 'Twenty Thousand Leagues Under the Sea — CHAPTER 10'),
    (11, 'TTLU-ch11', 'Twenty Thousand Leagues Under the Sea — CHAPTER 11'),
    (12, 'TTLU-ch12', 'Twenty Thousand Leagues Under the Sea — CHAPTER 12'),
    (13, 'TTLU-ch13', 'Twenty Thousand Leagues Under the Sea — CHAPTER 13'),
    (14, 'TTLU-ch14', 'Twenty Thousand Leagues Under the Sea — CHAPTER 14'),
    (15, 'TTLU-ch15', 'Twenty Thousand Leagues Under the Sea — CHAPTER 15'),
    (16, 'TTLU-ch16', 'Twenty Thousand Leagues Under the Sea — CHAPTER 16'),
    (17, 'TTLU-ch17', 'Twenty Thousand Leagues Under the Sea — CHAPTER 17'),
    (18, 'TTLU-ch18', 'Twenty Thousand Leagues Under the Sea — CHAPTER 18'),
    (19, 'TTLU-ch19', 'Twenty Thousand Leagues Under the Sea — CHAPTER 19'),
    (20, 'TTLU-ch20', 'Twenty Thousand Leagues Under the Sea — CHAPTER 20'),
    (21, 'TTLU-ch21', 'Twenty Thousand Leagues Under the Sea — CHAPTER 21'),
    (22, 'TTLU-ch22', 'Twenty Thousand Leagues Under the Sea — CHAPTER 22'),
    (23, 'TTLU-ch23', 'Twenty Thousand Leagues Under the Sea — CHAPTER 23'),
    (24, 'TTLU-ch24', 'Twenty Thousand Leagues Under the Sea — CHAPTER 24'),
    (25, 'TTLU-ch25', 'Twenty Thousand Leagues Under the Sea — CHAPTER 1'),
    (26, 'TTLU-ch26', 'Twenty Thousand Leagues Under the Sea — CHAPTER 2'),
    (27, 'TTLU-ch27', 'Twenty Thousand Leagues Under the Sea — CHAPTER 3'),
    (28, 'TTLU-ch28', 'Twenty Thousand Leagues Under the Sea — CHAPTER 4'),
    (29, 'TTLU-ch29', 'Twenty Thousand Leagues Under the Sea — CHAPTER 5'),
    (30, 'TTLU-ch30', 'Twenty Thousand Leagues Under the Sea — CHAPTER 6'),
    (31, 'TTLU-ch31', 'Twenty Thousand Leagues Under the Sea — CHAPTER 7'),
    (32, 'TTLU-ch32', 'Twenty Thousand Leagues Under the Sea — CHAPTER 8'),
    (33, 'TTLU-ch33', 'Twenty Thousand Leagues Under the Sea — CHAPTER 9'),
    (34, 'TTLU-ch34', 'Twenty Thousand Leagues Under the Sea — CHAPTER 10'),
    (35, 'TTLU-ch35', 'Twenty Thousand Leagues Under the Sea — CHAPTER 11'),
    (36, 'TTLU-ch36', 'Twenty Thousand Leagues Under the Sea — CHAPTER 12'),
    (37, 'TTLU-ch37', 'Twenty Thousand Leagues Under the Sea — CHAPTER 13'),
    (38, 'TTLU-ch38', 'Twenty Thousand Leagues Under the Sea — CHAPTER 14'),
    (39, 'TTLU-ch39', 'Twenty Thousand Leagues Under the Sea — CHAPTER 15'),
    (40, 'TTLU-ch40', 'Twenty Thousand Leagues Under the Sea — CHAPTER 16'),
    (41, 'TTLU-ch41', 'Twenty Thousand Leagues Under the Sea — CHAPTER 17'),
    (42, 'TTLU-ch42', 'Twenty Thousand Leagues Under the Sea — CHAPTER 18'),
    (43, 'TTLU-ch43', 'Twenty Thousand Leagues Under the Sea — CHAPTER 19'),
    (44, 'TTLU-ch44', 'Twenty Thousand Leagues Under the Sea — CHAPTER 20'),
    (45, 'TTLU-ch45', 'Twenty Thousand Leagues Under the Sea — CHAPTER 21'),
    (46, 'TTLU-ch46', 'Twenty Thousand Leagues Under the Sea — CHAPTER 22'),
    (47, 'TTLU-ch47', 'Twenty Thousand Leagues Under the Sea — CHAPTER 23'),
    (48, 'JCE-ch01', 'A Journey to the Center of the Earth — CHAPTER I'),
    (49, 'JCE-ch02', 'A Journey to the Center of the Earth — CHAPTER II'),
    (50, 'JCE-ch03', 'A Journey to the Center of the Earth — CHAPTER III'),
    (51, 'JCE-ch04', 'A Journey to the Center of the Earth — CHAPTER IV'),
    (52, 'JCE-ch05', 'A Journey to the Center of the Earth — CHAPTER V'),
    (53, 'JCE-ch06', 'A Journey to the Center of the Earth — CHAPTER VI'),
    (54, 'JCE-ch07', 'A Journey to the Center of the Earth — CHAPTER VII'),
    (55, 'JCE-ch08', 'A Journey to the Center of the Earth — CHAPTER VIII'),
    (56, 'JCE-ch09', 'A Journey to the Center of the Earth — CHAPTER IX'),
    (57, 'JCE-ch10', 'A Journey to the Center of the Earth — CHAPTER X'),
    (58, 'JCE-ch11', 'A Journey to the Center of the Earth — CHAPTER XI'),
    (59, 'JCE-ch12', 'A Journey to the Center of the Earth — CHAPTER XII'),
    (60, 'JCE-ch13', 'A Journey to the Center of the Earth — CHAPTER XIII'),
    (61, 'JCE-ch14', 'A Journey to the Center of the Earth — CHAPTER XIV'),
    (62, 'JCE-ch15', 'A Journey to the Center of the Earth — CHAPTER XV'),
    (63, 'JCE-ch16', 'A Journey to the Center of the Earth — CHAPTER XVI'),
    (64, 'JCE-ch17', 'A Journey to the Center of the Earth — CHAPTER XVII'),
    (65, 'JCE-ch18', 'A Journey to the Center of the Earth — CHAPTER XVIII'),
    (66, 'JCE-ch19', 'A Journey to the Center of the Earth — CHAPTER XIX'),
    (67, 'JCE-ch20', 'A Journey to the Center of the Earth — CHAPTER XX'),
    (68, 'JCE-ch21', 'A Journey to the Center of the Earth — CHAPTER XXI'),
    (69, 'JCE-ch22', 'A Journey to the Center of the Earth — CHAPTER XXII'),
    (70, 'JCE-ch23', 'A Journey to the Center of the Earth — CHAPTER XXIII'),
    (71, 'JCE-ch24', 'A Journey to the Center of the Earth — CHAPTER XXIV'),
    (72, 'JCE-ch25', 'A Journey to the Center of the Earth — CHAPTER XXV'),
    (73, 'JCE-ch26', 'A Journey to the Center of the Earth — CHAPTER XXVI'),
    (74, 'JCE-ch27', 'A Journey to the Center of the Earth — CHAPTER XXVII'),
    (75, 'JCE-ch28', 'A Journey to the Center of the Earth — CHAPTER XXVIII'),
    (76, 'JCE-ch29', 'A Journey to the Center of the Earth — CHAPTER XXIX'),
    (77, 'JCE-ch30', 'A Journey to the Center of the Earth — CHAPTER XXX'),
    (78, 'JCE-ch31', 'A Journey to the Center of the Earth — CHAPTER XXXI'),
    (79, 'JCE-ch32', 'A Journey to the Center of the Earth — CHAPTER XXXII'),
    (80, 'JCE-ch33', 'A Journey to the Center of the Earth — CHAPTER XXXIII'),
    (81, 'JCE-ch34', 'A Journey to the Center of the Earth — CHAPTER XXXIV'),
    (82, 'JCE-ch35', 'A Journey to the Center of the Earth — CHAPTER XXXV'),
    (83, 'JCE-ch36', 'A Journey to the Center of the Earth — CHAPTER XXXVI'),
    (84, 'JCE-ch37', 'A Journey to the Center of the Earth — CHAPTER XXXVII'),
    (85, 'JCE-ch38', 'A Journey to the Center of the Earth — CHAPTER XXXVIII'),
    (86, 'JCE-ch39', 'A Journey to the Center of the Earth — CHAPTER XXXIX'),
    (87, 'JCE-ch40', 'A Journey to the Center of the Earth — CHAPTER XL'),
    (88, 'JCE-ch41', 'A Journey to the Center of the Earth — CHAPTER XLI'),
    (89, 'JCE-ch42', 'A Journey to the Center of the Earth — CHAPTER XLII'),
    (90, 'JCE-ch43', 'A Journey to the Center of the Earth — CHAPTER XLIII'),
    (91, 'JCE-ch44', 'A Journey to the Center of the Earth — CHAPTER XLIV'),
    (92, 'JCE-ch45', 'A Journey to the Center of the Earth — CHAPTER XLV'),
    (93, 'AWED-ch01', 'Around the World in Eighty Days — CHAPTER I'),
    (94, 'AWED-ch02', 'Around the World in Eighty Days — CHAPTER II'),
    (95, 'AWED-ch03', 'Around the World in Eighty Days — CHAPTER III'),
    (96, 'AWED-ch04', 'Around the World in Eighty Days — CHAPTER IV'),
    (97, 'AWED-ch05', 'Around the World in Eighty Days — CHAPTER V'),
    (98, 'AWED-ch06', 'Around the World in Eighty Days — CHAPTER VI'),
    (99, 'AWED-ch07', 'Around the World in Eighty Days — CHAPTER VII'),
    (100, 'AWED-ch08', 'Around the World in Eighty Days — CHAPTER VIII'),
    (101, 'AWED-ch09', 'Around the World in Eighty Days — CHAPTER IX'),
    (102, 'AWED-ch10', 'Around the World in Eighty Days — CHAPTER X'),
    (103, 'AWED-ch11', 'Around the World in Eighty Days — CHAPTER XI'),
    (104, 'AWED-ch12', 'Around the World in Eighty Days — CHAPTER XII'),
    (105, 'AWED-ch13', 'Around the World in Eighty Days — CHAPTER XIII'),
    (106, 'AWED-ch14', 'Around the World in Eighty Days — CHAPTER XIV'),
    (107, 'AWED-ch15', 'Around the World in Eighty Days — CHAPTER XV'),
    (108, 'AWED-ch16', 'Around the World in Eighty Days — CHAPTER XVI'),
    (109, 'AWED-ch17', 'Around the World in Eighty Days — CHAPTER XVII'),
    (110, 'AWED-ch18', 'Around the World in Eighty Days — CHAPTER XVIII'),
    (111, 'AWED-ch19', 'Around the World in Eighty Days — CHAPTER XIX'),
    (112, 'AWED-ch20', 'Around the World in Eighty Days — CHAPTER XX'),
    (113, 'AWED-ch21', 'Around the World in Eighty Days — CHAPTER XXI'),
    (114, 'AWED-ch22', 'Around the World in Eighty Days — CHAPTER XXII'),
    (115, 'AWED-ch23', 'Around the World in Eighty Days — CHAPTER XXIII'),
    (116, 'AWED-ch24', 'Around the World in Eighty Days — CHAPTER XXIV'),
    (117, 'AWED-ch25', 'Around the World in Eighty Days — CHAPTER XXV'),
    (118, 'AWED-ch26', 'Around the World in Eighty Days — CHAPTER XXVI'),
    (119, 'AWED-ch27', 'Around the World in Eighty Days — CHAPTER XXVII'),
    (120, 'AWED-ch28', 'Around the World in Eighty Days — CHAPTER XXVIII'),
    (121, 'AWED-ch29', 'Around the World in Eighty Days — CHAPTER XXIX'),
    (122, 'AWED-ch30', 'Around the World in Eighty Days — CHAPTER XXX'),
    (123, 'AWED-ch31', 'Around the World in Eighty Days — CHAPTER XXXI'),
    (124, 'AWED-ch32', 'Around the World in Eighty Days — CHAPTER XXXII'),
    (125, 'AWED-ch33', 'Around the World in Eighty Days — CHAPTER XXXIII'),
    (126, 'AWED-ch34', 'Around the World in Eighty Days — CHAPTER XXXIV'),
    (127, 'AWED-ch35', 'Around the World in Eighty Days — CHAPTER XXXV'),
    (128, 'AWED-ch36', 'Around the World in Eighty Days — CHAPTER XXXVI'),
    (129, 'AWED-ch37', 'Around the World in Eighty Days — CHAPTER XXXVII'),
    (130, 'MI-ch01', 'The Mysterious Island — CHAPTER 1'),
    (131, 'MI-ch02', 'The Mysterious Island — CHAPTER 2'),
    (132, 'MI-ch03', 'The Mysterious Island — CHAPTER 3'),
    (133, 'MI-ch04', 'The Mysterious Island — CHAPTER 4'),
    (134, 'MI-ch05', 'The Mysterious Island — CHAPTER 5'),
    (135, 'MI-ch06', 'The Mysterious Island — CHAPTER 6'),
    (136, 'MI-ch07', 'The Mysterious Island — CHAPTER 7'),
    (137, 'MI-ch08', 'The Mysterious Island — CHAPTER 8'),
    (138, 'MI-ch09', 'The Mysterious Island — CHAPTER 9'),
    (139, 'MI-ch10', 'The Mysterious Island — CHAPTER 10'),
    (140, 'MI-ch11', 'The Mysterious Island — CHAPTER 11'),
    (141, 'MI-ch12', 'The Mysterious Island — CHAPTER 12'),
    (142, 'MI-ch13', 'The Mysterious Island — CHAPTER 13'),
    (143, 'MI-ch14', 'The Mysterious Island — CHAPTER 14'),
    (144, 'MI-ch15', 'The Mysterious Island — CHAPTER 15'),
    (145, 'MI-ch16', 'The Mysterious Island — CHAPTER 16'),
    (146, 'MI-ch17', 'The Mysterious Island — CHAPTER 17'),
    (147, 'MI-ch18', 'The Mysterious Island — CHAPTER 18'),
    (148, 'MI-ch19', 'The Mysterious Island — CHAPTER 19'),
    (149, 'MI-ch20', 'The Mysterious Island — CHAPTER 20'),
    (150, 'MI-ch21', 'The Mysterious Island — CHAPTER 21'),
    (151, 'MI-ch22', 'The Mysterious Island — CHAPTER 22'),
    (152, 'MI-ch23', 'The Mysterious Island — CHAPTER 1'),
    (153, 'MI-ch24', 'The Mysterious Island — CHAPTER 2'),
    (154, 'MI-ch25', 'The Mysterious Island — CHAPTER 3'),
    (155, 'MI-ch26', 'The Mysterious Island — CHAPTER 4'),
    (156, 'MI-ch27', 'The Mysterious Island — CHAPTER 5'),
    (157, 'MI-ch28', 'The Mysterious Island — CHAPTER 6'),
    (158, 'MI-ch29', 'The Mysterious Island — CHAPTER 7'),
    (159, 'MI-ch30', 'The Mysterious Island — CHAPTER 8'),
    (160, 'MI-ch31', 'The Mysterious Island — CHAPTER 9'),
    (161, 'MI-ch32', 'The Mysterious Island — CHAPTER 10'),
    (162, 'MI-ch33', 'The Mysterious Island — CHAPTER 11'),
    (163, 'MI-ch34', 'The Mysterious Island — CHAPTER 12'),
    (164, 'MI-ch35', 'The Mysterious Island — CHAPTER 13'),
    (165, 'MI-ch36', 'The Mysterious Island — CHAPTER 14'),
    (166, 'MI-ch37', 'The Mysterious Island — CHAPTER 15'),
    (167, 'MI-ch38', 'The Mysterious Island — CHAPTER 16'),
    (168, 'MI-ch39', 'The Mysterious Island — CHAPTER 17'),
    (169, 'MI-ch40', 'The Mysterious Island — CHAPTER 18'),
    (170, 'MI-ch41', 'The Mysterious Island — CHAPTER 19'),
    (171, 'MI-ch42', 'The Mysterious Island — CHAPTER 20'),
    (172, 'MI-ch43', 'The Mysterious Island — CHAPTER 1'),
    (173, 'MI-ch44', 'The Mysterious Island — CHAPTER 2'),
    (174, 'MI-ch45', 'The Mysterious Island — CHAPTER 3'),
    (175, 'MI-ch46', 'The Mysterious Island — CHAPTER 4'),
    (176, 'MI-ch47', 'The Mysterious Island — CHAPTER 5'),
    (177, 'MI-ch48', 'The Mysterious Island — CHAPTER 6'),
    (178, 'MI-ch49', 'The Mysterious Island — CHAPTER 7'),
    (179, 'MI-ch50', 'The Mysterious Island — CHAPTER 8'),
    (180, 'MI-ch51', 'The Mysterious Island — CHAPTER 9'),
    (181, 'MI-ch52', 'The Mysterious Island — CHAPTER 10'),
    (182, 'MI-ch53', 'The Mysterious Island — CHAPTER 11'),
    (183, 'MI-ch54', 'The Mysterious Island — CHAPTER 12'),
    (184, 'MI-ch55', 'The Mysterious Island — CHAPTER 13'),
    (185, 'MI-ch56', 'The Mysterious Island — CHAPTER 14'),
    (186, 'MI-ch57', 'The Mysterious Island — CHAPTER 15'),
    (187, 'MI-ch58', 'The Mysterious Island — CHAPTER 16'),
    (188, 'MI-ch59', 'The Mysterious Island — CHAPTER 17'),
    (189, 'MI-ch60', 'The Mysterious Island — CHAPTER 18'),
    (190, 'MI-ch61', 'The Mysterious Island — CHAPTER 19'),
    (191, 'MI-ch62', 'The Mysterious Island — CHAPTER 20'),
    (192, 'FEM-ch01', 'From the Earth to the Moon — CHAPTER I'),
    (193, 'FEM-ch02', 'From the Earth to the Moon — CHAPTER II'),
    (194, 'FEM-ch03', 'From the Earth to the Moon — CHAPTER III'),
    (195, 'FEM-ch04', 'From the Earth to the Moon — CHAPTER IV'),
    (196, 'FEM-ch05', 'From the Earth to the Moon — CHAPTER V'),
    (197, 'FEM-ch06', 'From the Earth to the Moon — CHAPTER VI'),
    (198, 'FEM-ch07', 'From the Earth to the Moon — CHAPTER VII'),
    (199, 'FEM-ch08', 'From the Earth to the Moon — CHAPTER VIII'),
    (200, 'FEM-ch09', 'From the Earth to the Moon — CHAPTER IX'),
    (201, 'FEM-ch10', 'From the Earth to the Moon — CHAPTER X'),
    (202, 'FEM-ch11', 'From the Earth to the Moon — CHAPTER XI'),
    (203, 'FEM-ch12', 'From the Earth to the Moon — CHAPTER XII'),
    (204, 'FEM-ch13', 'From the Earth to the Moon — CHAPTER XIII'),
    (205, 'FEM-ch14', 'From the Earth to the Moon — CHAPTER XIV'),
    (206, 'FEM-ch15', 'From the Earth to the Moon — CHAPTER XV'),
    (207, 'FEM-ch16', 'From the Earth to the Moon — CHAPTER XVI'),
    (208, 'FEM-ch17', 'From the Earth to the Moon — CHAPTER XVII'),
    (209, 'FEM-ch18', 'From the Earth to the Moon — CHAPTER XVIII'),
    (210, 'FEM-ch19', 'From the Earth to the Moon — CHAPTER XIX'),
    (211, 'FEM-ch20', 'From the Earth to the Moon — CHAPTER XX'),
    (212, 'FEM-ch21', 'From the Earth to the Moon — CHAPTER XXI'),
    (213, 'FEM-ch22', 'From the Earth to the Moon — CHAPTER XXII'),
    (214, 'FEM-ch23', 'From the Earth to the Moon — CHAPTER XXIII'),
    (215, 'FEM-ch24', 'From the Earth to the Moon — CHAPTER XXIV'),
    (216, 'FEM-ch25', 'From the Earth to the Moon — CHAPTER XXV'),
    (217, 'FEM-ch26', 'From the Earth to the Moon — CHAPTER XXVI'),
    (218, 'FEM-ch27', 'From the Earth to the Moon — CHAPTER XXVII'),
    (219, 'FEM-ch28', 'From the Earth to the Moon — CHAPTER XXVIII'),
    (220, 'RM-ch01', 'Round the Moon — CHAPTER I'),
    (221, 'RM-ch02', 'Round the Moon — CHAPTER II'),
    (222, 'RM-ch03', 'Round the Moon — CHAPTER III'),
    (223, 'RM-ch04', 'Round the Moon — CHAPTER IV'),
    (224, 'RM-ch05', 'Round the Moon — CHAPTER V'),
    (225, 'RM-ch06', 'Round the Moon — CHAPTER VI'),
    (226, 'RM-ch07', 'Round the Moon — CHAPTER VII'),
    (227, 'RM-ch08', 'Round the Moon — CHAPTER VIII'),
    (228, 'RM-ch09', 'Round the Moon — CHAPTER IX'),
    (229, 'RM-ch10', 'Round the Moon — CHAPTER X'),
    (230, 'RM-ch11', 'Round the Moon — CHAPTER XI'),
    (231, 'RM-ch12', 'Round the Moon — CHAPTER XII'),
    (232, 'RM-ch13', 'Round the Moon — CHAPTER XIII'),
    (233, 'RM-ch14', 'Round the Moon — CHAPTER XIV'),
    (234, 'RM-ch15', 'Round the Moon — CHAPTER XV'),
    (235, 'RM-ch16', 'Round the Moon — CHAPTER XVI'),
    (236, 'RM-ch17', 'Round the Moon — CHAPTER XVII'),
    (237, 'RM-ch18', 'Round the Moon — CHAPTER XVIII'),
    (238, 'RM-ch19', 'Round the Moon — CHAPTER XIX'),
    (239, 'RM-ch20', 'Round the Moon — CHAPTER XX'),
    (240, 'RM-ch21', 'Round the Moon — CHAPTER XXI'),
    (241, 'RM-ch22', 'Round the Moon — CHAPTER XXII'),
    (242, 'RM-ch23', 'Round the Moon — CHAPTER XXIII'),
    (243, 'VB', 'A Voyage in a Balloon'),
    (244, 'DOSE-ch01', "Doctor Ox's Experiment — CHAPTER I"),
    (245, 'DOSE-ch02', "Doctor Ox's Experiment — CHAPTER II"),
    (246, 'DOSE-ch03', "Doctor Ox's Experiment — CHAPTER III"),
    (247, 'DOSE-ch04', "Doctor Ox's Experiment — CHAPTER IV"),
    (248, 'DOSE-ch05', "Doctor Ox's Experiment — CHAPTER V"),
    (249, 'DOSE-ch06', "Doctor Ox's Experiment — CHAPTER VI"),
    (250, 'DOSE-ch07', "Doctor Ox's Experiment — CHAPTER VII"),
    (251, 'DOSE-ch08', "Doctor Ox's Experiment — CHAPTER VIII"),
    (252, 'DOSE-ch09', "Doctor Ox's Experiment — CHAPTER IX"),
    (253, 'DOSE-ch10', "Doctor Ox's Experiment — CHAPTER X"),
    (254, 'DOSE-ch11', "Doctor Ox's Experiment — CHAPTER XI"),
    (255, 'DOSE-ch12', "Doctor Ox's Experiment — CHAPTER XII"),
    (256, 'DOSE-ch13', "Doctor Ox's Experiment — CHAPTER XIII"),
    (257, 'DOSE-ch14', "Doctor Ox's Experiment — CHAPTER XIV"),
    (258, 'DOSE-ch15', "Doctor Ox's Experiment — CHAPTER XV"),
    (259, 'DOSE-ch16', "Doctor Ox's Experiment — CHAPTER XVI"),
    (260, 'DOSE-ch17', 'Doctor Ox‘s Experiment — CHAPTER XVII. IN WHICH DOCTOR OX’S THEORY IS EXPLAINED'),
    (261, 'MZ-ch01', 'Master Zacharius — CHAPTER I'),
    (262, 'MZ-ch02', 'Master Zacharius — CHAPTER II'),
    (263, 'MZ-ch03', 'Master Zacharius — CHAPTER III'),
    (264, 'MZ-ch04', 'Master Zacharius — CHAPTER IV'),
    (265, 'MZ-ch05', 'Master Zacharius — CHAPTER V'),
    (266, 'DA', 'A Drama in the Air'),
    (267, 'WAI-ch01', 'A Winter Amid the Ice — CHAPTER I'),
    (268, 'WAI-ch02', 'A Winter Amid the Ice — CHAPTER II'),
    (269, 'WAI-ch03', 'A Winter Amid the Ice — CHAPTER III'),
    (270, 'WAI-ch04', 'A Winter Amid the Ice — CHAPTER IV'),
    (271, 'WAI-ch05', 'A Winter Amid the Ice — CHAPTER V'),
    (272, 'WAI-ch06', 'A Winter Amid the Ice — CHAPTER VI'),
    (273, 'WAI-ch07', 'A Winter Amid the Ice — CHAPTER VII'),
    (274, 'WAI-ch08', 'A Winter Amid the Ice — CHAPTER VIII'),
    (275, 'WAI-ch09', 'A Winter Amid the Ice — CHAPTER IX'),
    (276, 'WAI-ch10', 'A Winter Amid the Ice — CHAPTER X'),
    (277, 'WAI-ch11', 'A Winter Amid the Ice — CHAPTER XI'),
    (278, 'WAI-ch12', 'A Winter Amid the Ice — CHAPTER XII'),
    (279, 'WAI-ch13', 'A Winter Amid the Ice — CHAPTER XIII'),
    (280, 'WAI-ch14', 'A Winter Amid the Ice — CHAPTER XIV'),
    (281, 'WAI-ch15', 'A Winter Amid the Ice — CHAPTER XV'),
    (282, 'WAI-ch16', 'A Winter Amid the Ice — CHAPTER XVI'),
    (283, 'AMB', 'Ascent of Mont Blanc'),
    (284, 'AM-ch01', 'An Antarctic Mystery — CHAPTER I. THE KERGUELEN ISLANDS'),
    (285, 'AM-ch02', 'An Antarctic Mystery — CHAPTER II. THE SCHOONER _HALBRANE_'),
    (286, 'AM-ch03', 'An Antarctic Mystery — CHAPTER III. CAPTAIN LEN GUY'),
    (287, 'AM-ch04', 'An Antarctic Mystery — CHAPTER IV. FROM THE KERGUELEN ISLES TO PRINCE EDWARD ISLAND'),
    (288, 'AM-ch05', "An Antarctic Mystery — CHAPTER V. EDGAR POE'S ROMANCE"),
    (289, 'AM-ch06', 'An Antarctic Mystery — CHAPTER VI. AN OCEAN WAIF'),
    (290, 'AM-ch07', "An Antarctic Mystery — CHAPTER VII. TRISTAN D'ACUNHA"),
    (291, 'AM-ch08', 'An Antarctic Mystery — CHAPTER VIII. BOUND FOR THE FALKLANDS'),
    (292, 'AM-ch09', 'An Antarctic Mystery — CHAPTER IX. FITTING OUT THE _HALBRANE_'),
    (293, 'AM-ch10', 'An Antarctic Mystery — CHAPTER X. THE OUTSET OF THE ENTERPRISE'),
    (294, 'AM-ch11', 'An Antarctic Mystery — CHAPTER XI. FROM THE SANDWICH ISLANDS TO THE POLAR CIRCLE'),
    (295, 'AM-ch12', 'An Antarctic Mystery — CHAPTER XII. BETWEEN THE POLAR CIRCLE AND THE ICE WALL'),
    (296, 'AM-ch13', 'An Antarctic Mystery — CHAPTER XIII. ALONG THE FRONT OF THE ICEBERGS'),
    (297, 'AM-ch14', 'An Antarctic Mystery — CHAPTER XIV. A VOICE IN A DREAM'),
    (298, 'AM-ch15', 'An Antarctic Mystery — CHAPTER XV. BENNET ISLET'),
    (299, 'AM-ch16', 'An Antarctic Mystery — CHAPTER XVI, TSALAL ISLAND'),
    (300, 'AM-ch17', 'An Antarctic Mystery — CHAPTER XVII. AND PYM?'),
    (301, 'AM-ch18', 'An Antarctic Mystery — CHAPTER XVIII. A REVELATION'),
    (302, 'AM-ch19', 'An Antarctic Mystery — CHAPTER XIX. LAND?'),
    (303, 'AM-ch20', 'An Antarctic Mystery — CHAPTER XX, “UNMERCIFUL DISASTER”'),
    (304, 'AM-ch21', 'An Antarctic Mystery — CHAPTER XXI. AMID THE MISTS'),
    (305, 'AM-ch22', 'An Antarctic Mystery — CHAPTER XXII. IN CAMP'),
    (306, 'AM-ch23', 'An Antarctic Mystery — CHAPTER XXIII. FOUND AT LAST'),
    (307, 'AM-ch24', 'An Antarctic Mystery — CHAPTER XXIV. ELEVEN YEARS IN A FEW PAGES'),
    (308, 'AM-ch25', 'An Antarctic Mystery — CHAPTER XXV. “WE WERE THE FIRST.”'),
    (309, 'AM-ch26', 'An Antarctic Mystery — CHAPTER XXVI. A LITTLE REMNANT'),
    (310, 'DSCF-ch01', 'Dick Sand: A Captain at Fifteen — CHAPTER I'),
    (311, 'DSCF-ch02', 'Dick Sand: A Captain at Fifteen — CHAPTER II'),
    (312, 'DSCF-ch03', 'Dick Sand: A Captain at Fifteen — CHAPTER III'),
    (313, 'DSCF-ch04', 'Dick Sand: A Captain at Fifteen — CHAPTER IV'),
    (314, 'DSCF-ch05', 'Dick Sand: A Captain at Fifteen — CHAPTER V'),
    (315, 'DSCF-ch06', 'Dick Sand: A Captain at Fifteen — CHAPTER VI'),
    (316, 'DSCF-ch07', 'Dick Sand: A Captain at Fifteen — CHAPTER VII'),
    (317, 'DSCF-ch08', 'Dick Sand: A Captain at Fifteen — CHAPTER VIII'),
    (318, 'DSCF-ch09', 'Dick Sand: A Captain at Fifteen — CHAPTER IX'),
    (319, 'DSCF-ch10', 'Dick Sand: A Captain at Fifteen — CHAPTER X'),
    (320, 'DSCF-ch11', 'Dick Sand: A Captain at Fifteen — CHAPTER XI'),
    (321, 'DSCF-ch12', 'Dick Sand: A Captain at Fifteen — CHAPTER XII'),
    (322, 'DSCF-ch13', 'Dick Sand: A Captain at Fifteen — CHAPTER XIII'),
    (323, 'DSCF-ch14', 'Dick Sand: A Captain at Fifteen — CHAPTER XIV'),
    (324, 'DSCF-ch15', 'Dick Sand: A Captain at Fifteen — CHAPTER XV'),
    (325, 'DSCF-ch16', 'Dick Sand: A Captain at Fifteen — CHAPTER XVI'),
    (326, 'DSCF-ch17', 'Dick Sand: A Captain at Fifteen — CHAPTER XVII'),
    (327, 'DSCF-ch18', 'Dick Sand: A Captain at Fifteen — CHAPTER XVIII'),
    (328, 'DSCF-ch19', 'Dick Sand: A Captain at Fifteen — CHAPTER I'),
    (329, 'DSCF-ch20', 'Dick Sand: A Captain at Fifteen — CHAPTER II'),
    (330, 'DSCF-ch21', 'Dick Sand: A Captain at Fifteen — CHAPTER III'),
    (331, 'DSCF-ch22', 'Dick Sand: A Captain at Fifteen — CHAPTER IV'),
    (332, 'DSCF-ch23', 'Dick Sand: A Captain at Fifteen — CHAPTER V'),
    (333, 'DSCF-ch24', 'Dick Sand: A Captain at Fifteen — CHAPTER VI'),
    (334, 'DSCF-ch25', 'Dick Sand: A Captain at Fifteen — CHAPTER VII'),
    (335, 'DSCF-ch26', 'Dick Sand: A Captain at Fifteen — CHAPTER VIII'),
    (336, 'DSCF-ch27', 'Dick Sand: A Captain at Fifteen — CHAPTER IX'),
    (337, 'DSCF-ch28', 'Dick Sand: A Captain at Fifteen — CHAPTER X'),
    (338, 'DSCF-ch29', 'Dick Sand: A Captain at Fifteen — CHAPTER XI'),
    (339, 'DSCF-ch30', 'Dick Sand: A Captain at Fifteen — CHAPTER XII'),
    (340, 'DSCF-ch31', 'Dick Sand: A Captain at Fifteen — CHAPTER XIII'),
    (341, 'DSCF-ch32', 'Dick Sand: A Captain at Fifteen — CHAPTER XIV'),
    (342, 'DSCF-ch33', 'Dick Sand: A Captain at Fifteen — CHAPTER XV'),
    (343, 'DSCF-ch34', 'Dick Sand: A Captain at Fifteen — CHAPTER XVI'),
    (344, 'DSCF-ch35', 'Dick Sand: A Captain at Fifteen — CHAPTER XVII'),
    (345, 'DSCF-ch36', 'Dick Sand: A Captain at Fifteen — CHAPTER XVIII'),
    (346, 'DSCF-ch37', 'Dick Sand: A Captain at Fifteen — CHAPTER XIX'),
    (347, 'DSCF-ch38', 'Dick Sand: A Captain at Fifteen — CHAPTER XX'),
    (348, 'EHLA-ch01', 'Eight Hundred Leagues on the Amazon — CHAPTER I. A CAPTAIN OF THE WOODS'),
    (349, 'EHLA-ch02', 'Eight Hundred Leagues on the Amazon — CHAPTER II. ROBBER AND ROBBED'),
    (350, 'EHLA-ch03', 'Eight Hundred Leagues on the Amazon — CHAPTER III. THE GARRAL FAMILY'),
    (351, 'EHLA-ch04', 'Eight Hundred Leagues on the Amazon — CHAPTER IV. HESITATION'),
    (352, 'EHLA-ch05', 'Eight Hundred Leagues on the Amazon — CHAPTER V. THE AMAZON'),
    (353, 'EHLA-ch06', 'Eight Hundred Leagues on the Amazon — CHAPTER VI. A FOREST ON THE GROUND'),
    (354, 'EHLA-ch07', 'Eight Hundred Leagues on the Amazon — CHAPTER VII. FOLLOWING A LIANA'),
    (355, 'EHLA-ch08', 'Eight Hundred Leagues on the Amazon — CHAPTER VIII. THE JANGADA'),
    (356, 'EHLA-ch09', 'Eight Hundred Leagues on the Amazon — CHAPTER IX. THE EVENING OF THE FIFTH OF JUNE'),
    (357, 'EHLA-ch10', 'Eight Hundred Leagues on the Amazon — CHAPTER X. FROM IQUITOS TO PEVAS'),
    (358, 'EHLA-ch11', 'Eight Hundred Leagues on the Amazon — CHAPTER XI. FROM PEVAS TO THE FRONTIER'),
    (359, 'EHLA-ch12', 'Eight Hundred Leagues on the Amazon — CHAPTER XII. FRAGOSO AT WORK'),
    (360, 'EHLA-ch13', 'Eight Hundred Leagues on the Amazon — CHAPTER XIII. TORRES'),
    (361, 'EHLA-ch14', 'Eight Hundred Leagues on the Amazon — CHAPTER XIV. STILL DESCENDING'),
    (362, 'EHLA-ch15', 'Eight Hundred Leagues on the Amazon — CHAPTER XV. THE CONTINUED DESCENT'),
    (363, 'EHLA-ch16', 'Eight Hundred Leagues on the Amazon — CHAPTER XVI. EGA'),
    (364, 'EHLA-ch17', 'Eight Hundred Leagues on the Amazon — CHAPTER XVII. AN ATTACK'),
    (365, 'EHLA-ch18', 'Eight Hundred Leagues on the Amazon — CHAPTER XVIII. THE ARRIVAL DINNER'),
    (366, 'EHLA-ch19', 'Eight Hundred Leagues on the Amazon — CHAPTER XIX. ANCIENT HISTORY'),
    (367, 'EHLA-ch20', 'Eight Hundred Leagues on the Amazon — CHAPTER XX. BETWEEN THE TWO MEN'),
    (368, 'EHLA-ch21', 'Eight Hundred Leagues on the Amazon — CHAPTER I. MANAOS'),
    (369, 'EHLA-ch22', 'Eight Hundred Leagues on the Amazon — CHAPTER II. THE FIRST MOMENTS'),
    (370, 'EHLA-ch23', 'Eight Hundred Leagues on the Amazon — CHAPTER III. RETROSPECTIVE'),
    (371, 'EHLA-ch24', 'Eight Hundred Leagues on the Amazon — CHAPTER IV. MORAL PROOFS'),
    (372, 'EHLA-ch25', 'Eight Hundred Leagues on the Amazon — CHAPTER V. MATERIAL PROOFS'),
    (373, 'EHLA-ch26', 'Eight Hundred Leagues on the Amazon — CHAPTER VI. THE LAST BLOW'),
    (374, 'EHLA-ch27', 'Eight Hundred Leagues on the Amazon — CHAPTER VII. RESOLUTIONS'),
    (375, 'EHLA-ch28', 'Eight Hundred Leagues on the Amazon — CHAPTER VIII. THE FIRST SEARCH'),
    (376, 'EHLA-ch29', 'Eight Hundred Leagues on the Amazon — CHAPTER IX. THE SECOND ATTEMPT'),
    (377, 'EHLA-ch30', 'Eight Hundred Leagues on the Amazon — CHAPTER X. A CANNON SHOT'),
    (378, 'EHLA-ch31', 'Eight Hundred Leagues on the Amazon — CHAPTER XI. THE CONTENTS OF THE CASE'),
    (379, 'EHLA-ch32', 'Eight Hundred Leagues on the Amazon — CHAPTER XII. THE DOCUMENT'),
    (380, 'EHLA-ch33', 'Eight Hundred Leagues on the Amazon — CHAPTER XIII. IS IT A MATTER OF FIGURES?'),
    (381, 'EHLA-ch34', 'Eight Hundred Leagues on the Amazon — CHAPTER XIV. CHANCE!'),
    (382, 'EHLA-ch35', 'Eight Hundred Leagues on the Amazon — CHAPTER XV. THE LAST EFFORTS'),
    (383, 'EHLA-ch36', 'Eight Hundred Leagues on the Amazon — CHAPTER XVI. PREPARATIONS'),
    (384, 'EHLA-ch37', 'Eight Hundred Leagues on the Amazon — CHAPTER XVII. THE LAST NIGHT'),
    (385, 'EHLA-ch38', 'Eight Hundred Leagues on the Amazon — CHAPTER XVIII. FRAGOSO'),
    (386, 'EHLA-ch39', 'Eight Hundred Leagues on the Amazon — CHAPTER XIX. THE CRIME OF TIJUCO'),
    (387, 'EHLA-ch40', 'Eight Hundred Leagues on the Amazon — CHAPTER XX. THE LOWER AMAZON'),
    (388, 'FF-ch01', 'Facing the Flag — CHAPTER I'),
    (389, 'FF-ch02', 'Facing the Flag — CHAPTER II'),
    (390, 'FF-ch03', 'Facing the Flag — CHAPTER III'),
    (391, 'FF-ch04', 'Facing the Flag — CHAPTER IV'),
    (392, 'FF-ch05', 'Facing the Flag — CHAPTER V'),
    (393, 'FF-ch06', 'Facing the Flag — CHAPTER VI'),
    (394, 'FF-ch07', 'Facing the Flag — CHAPTER VII'),
    (395, 'FF-ch08', 'Facing the Flag — CHAPTER VIII'),
    (396, 'FF-ch09', 'Facing the Flag — CHAPTER IX'),
    (397, 'FF-ch10', 'Facing the Flag — CHAPTER X'),
    (398, 'FF-ch11', 'Facing the Flag — CHAPTER XI'),
    (399, 'FF-ch12', 'Facing the Flag — CHAPTER XII'),
    (400, 'FF-ch13', 'Facing the Flag — CHAPTER XIII'),
    (401, 'FF-ch14', 'Facing the Flag — CHAPTER XIV'),
    (402, 'FF-ch15', 'Facing the Flag — CHAPTER XV'),
    (403, 'FF-ch16', 'Facing the Flag — CHAPTER XVI'),
    (404, 'FF-ch17', 'Facing the Flag — CHAPTER XVII'),
    (405, 'FF-ch18', 'Facing the Flag — CHAPTER XVIII'),
    (406, 'FWB-ch01', 'Five Weeks in a Balloon — CHAPTER FIRST'),
    (407, 'FWB-ch02', 'Five Weeks in a Balloon — CHAPTER SECOND'),
    (408, 'FWB-ch03', 'Five Weeks in a Balloon — CHAPTER THIRD'),
    (409, 'FWB-ch04', 'Five Weeks in a Balloon — CHAPTER FOURTH'),
    (410, 'FWB-ch05', 'Five Weeks in a Balloon — CHAPTER FIFTH'),
    (411, 'FWB-ch06', 'Five Weeks in a Balloon — CHAPTER SIXTH'),
    (412, 'FWB-ch07', 'Five Weeks in a Balloon — CHAPTER SEVENTH'),
    (413, 'FWB-ch08', 'Five Weeks in a Balloon — CHAPTER EIGHTH'),
    (414, 'FWB-ch09', 'Five Weeks in a Balloon — CHAPTER NINTH'),
    (415, 'FWB-ch10', 'Five Weeks in a Balloon — CHAPTER TENTH'),
    (416, 'FWB-ch11', 'Five Weeks in a Balloon — CHAPTER ELEVENTH'),
    (417, 'FWB-ch12', 'Five Weeks in a Balloon — CHAPTER TWELFTH'),
    (418, 'FWB-ch13', 'Five Weeks in a Balloon — CHAPTER THIRTEENTH'),
    (419, 'FWB-ch14', 'Five Weeks in a Balloon — CHAPTER FOURTEENTH'),
    (420, 'FWB-ch15', 'Five Weeks in a Balloon — CHAPTER FIFTEENTH'),
    (421, 'FWB-ch16', 'Five Weeks in a Balloon — CHAPTER SIXTEENTH'),
    (422, 'FWB-ch17', 'Five Weeks in a Balloon — CHAPTER SEVENTEENTH'),
    (423, 'FWB-ch18', 'Five Weeks in a Balloon — CHAPTER EIGHTEENTH'),
    (424, 'FWB-ch19', 'Five Weeks in a Balloon — CHAPTER NINETEENTH'),
    (425, 'FWB-ch20', 'Five Weeks in a Balloon — CHAPTER TWENTIETH'),
    (426, 'FWB-ch21', 'Five Weeks in a Balloon — CHAPTER TWENTY-FIRST'),
    (427, 'FWB-ch22', 'Five Weeks in a Balloon — CHAPTER TWENTY-SECOND'),
    (428, 'FWB-ch23', 'Five Weeks in a Balloon — CHAPTER TWENTY-THIRD'),
    (429, 'FWB-ch24', 'Five Weeks in a Balloon — CHAPTER TWENTY-FOURTH'),
    (430, 'FWB-ch25', 'Five Weeks in a Balloon — CHAPTER TWENTY-FIFTH'),
    (431, 'FWB-ch26', 'Five Weeks in a Balloon — CHAPTER TWENTY-SIXTH'),
    (432, 'FWB-ch27', 'Five Weeks in a Balloon — CHAPTER TWENTY-SEVENTH'),
    (433, 'FWB-ch28', 'Five Weeks in a Balloon — CHAPTER TWENTY-EIGHTH'),
    (434, 'FWB-ch29', 'Five Weeks in a Balloon — CHAPTER TWENTY-NINTH'),
    (435, 'FWB-ch30', 'Five Weeks in a Balloon — CHAPTER THIRTIETH'),
    (436, 'FWB-ch31', 'Five Weeks in a Balloon — CHAPTER THIRTY-FIRST'),
    (437, 'FWB-ch32', 'Five Weeks in a Balloon — CHAPTER THIRTY-SECOND'),
    (438, 'FWB-ch33', 'Five Weeks in a Balloon — CHAPTER THIRTY-THIRD'),
    (439, 'FWB-ch34', 'Five Weeks in a Balloon — CHAPTER THIRTY-FOURTH'),
    (440, 'FWB-ch35', 'Five Weeks in a Balloon — CHAPTER THIRTY-FIFTH'),
    (441, 'FWB-ch36', 'Five Weeks in a Balloon — CHAPTER THIRTY-SIXTH'),
    (442, 'FWB-ch37', 'Five Weeks in a Balloon — CHAPTER THIRTY-SEVENTH'),
    (443, 'FWB-ch38', 'Five Weeks in a Balloon — CHAPTER THIRTY-EIGHTH'),
    (444, 'FWB-ch39', 'Five Weeks in a Balloon — CHAPTER THIRTY-NINTH'),
    (445, 'FWB-ch40', 'Five Weeks in a Balloon — CHAPTER FORTIETH'),
    (446, 'FWB-ch41', 'Five Weeks in a Balloon — CHAPTER FORTY-FIRST'),
    (447, 'FWB-ch42', 'Five Weeks in a Balloon — CHAPTER FORTY-SECOND'),
    (448, 'FWB-ch43', 'Five Weeks in a Balloon — CHAPTER FORTY-THIRD'),
    (449, 'FWB-ch44', 'Five Weeks in a Balloon — CHAPTER FORTY-FOURTH'),
    (450, 'GM-ch01', 'Godfrey Morgan — CHAPTER I'),
    (451, 'GM-ch02', 'Godfrey Morgan — CHAPTER II'),
    (452, 'GM-ch03', 'Godfrey Morgan — CHAPTER III'),
    (453, 'GM-ch04', 'Godfrey Morgan — CHAPTER IV'),
    (454, 'GM-ch05', 'Godfrey Morgan — CHAPTER V'),
    (455, 'GM-ch06', 'Godfrey Morgan — CHAPTER VI'),
    (456, 'GM-ch07', 'Godfrey Morgan — CHAPTER VII'),
    (457, 'GM-ch08', 'Godfrey Morgan — CHAPTER VIII'),
    (458, 'GM-ch09', 'Godfrey Morgan — CHAPTER IX'),
    (459, 'GM-ch10', 'Godfrey Morgan — CHAPTER X'),
    (460, 'GM-ch11', 'Godfrey Morgan — CHAPTER XI'),
    (461, 'GM-ch12', 'Godfrey Morgan — CHAPTER XII'),
    (462, 'GM-ch13', 'Godfrey Morgan — CHAPTER XIII'),
    (463, 'GM-ch14', 'Godfrey Morgan — CHAPTER XIV'),
    (464, 'GM-ch15', 'Godfrey Morgan — CHAPTER XV'),
    (465, 'GM-ch16', 'Godfrey Morgan — CHAPTER XVI'),
    (466, 'GM-ch17', 'Godfrey Morgan — CHAPTER XVII'),
    (467, 'GM-ch18', 'Godfrey Morgan — CHAPTER XVIII'),
    (468, 'GM-ch19', 'Godfrey Morgan — CHAPTER XIX'),
    (469, 'GM-ch20', 'Godfrey Morgan — CHAPTER XX'),
    (470, 'GM-ch21', 'Godfrey Morgan — CHAPTER XXI'),
    (471, 'GM-ch22', 'Godfrey Morgan — CHAPTER XXII'),
    (472, 'ACH-ch01', 'The Adventures of Captain Hatteras — CHAPTER I'),
    (473, 'ACH-ch02', 'The Adventures of Captain Hatteras — CHAPTER II'),
    (474, 'ACH-ch03', 'The Adventures of Captain Hatteras — CHAPTER III'),
    (475, 'ACH-ch04', 'The Adventures of Captain Hatteras — CHAPTER IV'),
    (476, 'ACH-ch05', 'The Adventures of Captain Hatteras — CHAPTER V'),
    (477, 'ACH-ch06', 'The Adventures of Captain Hatteras — CHAPTER VI'),
    (478, 'ACH-ch07', 'The Adventures of Captain Hatteras — CHAPTER VII'),
    (479, 'ACH-ch08', 'The Adventures of Captain Hatteras — CHAPTER VIII'),
    (480, 'ACH-ch09', 'The Adventures of Captain Hatteras — CHAPTER IX'),
    (481, 'ACH-ch10', 'The Adventures of Captain Hatteras — CHAPTER X'),
    (482, 'ACH-ch11', 'The Adventures of Captain Hatteras — CHAPTER XI'),
    (483, 'ACH-ch12', 'The Adventures of Captain Hatteras — CHAPTER XII'),
    (484, 'ACH-ch13', 'The Adventures of Captain Hatteras — CHAPTER XIII'),
    (485, 'ACH-ch14', 'The Adventures of Captain Hatteras — CHAPTER XIV'),
    (486, 'ACH-ch15', 'The Adventures of Captain Hatteras — CHAPTER XV'),
    (487, 'ACH-ch16', 'The Adventures of Captain Hatteras — CHAPTER XVI'),
    (488, 'ACH-ch17', 'The Adventures of Captain Hatteras — CHAPTER XVII'),
    (489, 'ACH-ch18', 'The Adventures of Captain Hatteras — CHAPTER XVIII'),
    (490, 'ACH-ch19', 'The Adventures of Captain Hatteras — CHAPTER XIX'),
    (491, 'ACH-ch20', 'The Adventures of Captain Hatteras — CHAPTER XX'),
    (492, 'ACH-ch21', 'The Adventures of Captain Hatteras — CHAPTER XXI'),
    (493, 'ACH-ch22', 'The Adventures of Captain Hatteras — CHAPTER XXII'),
    (494, 'ACH-ch23', 'The Adventures of Captain Hatteras — CHAPTER XXIII'),
    (495, 'ACH-ch24', 'The Adventures of Captain Hatteras — CHAPTER XXIV'),
    (496, 'ACH-ch25', 'The Adventures of Captain Hatteras — CHAPTER XXV'),
    (497, 'ACH-ch26', 'The Adventures of Captain Hatteras — CHAPTER XXVI'),
    (498, 'ACH-ch27', 'The Adventures of Captain Hatteras — CHAPTER XXVII'),
    (499, 'ACH-ch28', 'The Adventures of Captain Hatteras — CHAPTER XXVIII'),
    (500, 'ACH-ch29', 'The Adventures of Captain Hatteras — CHAPTER XXIX'),
    (501, 'ACH-ch30', 'The Adventures of Captain Hatteras — CHAPTER XXX'),
    (502, 'ACH-ch31', 'The Adventures of Captain Hatteras — CHAPTER XXXI'),
    (503, 'ACH-ch32', 'The Adventures of Captain Hatteras — CHAPTER XXXII'),
    (504, 'ACH-ch33', 'The Adventures of Captain Hatteras — CHAPTER I'),
    (505, 'ACH-ch34', 'The Adventures of Captain Hatteras — CHAPTER II'),
    (506, 'ACH-ch35', 'The Adventures of Captain Hatteras — CHAPTER III'),
    (507, 'ACH-ch36', 'The Adventures of Captain Hatteras — CHAPTER IV'),
    (508, 'ACH-ch37', 'The Adventures of Captain Hatteras — CHAPTER V'),
    (509, 'ACH-ch38', 'The Adventures of Captain Hatteras — CHAPTER VI'),
    (510, 'ACH-ch39', 'The Adventures of Captain Hatteras — CHAPTER VII'),
    (511, 'ACH-ch40', 'The Adventures of Captain Hatteras — CHAPTER VIII'),
    (512, 'ACH-ch41', 'The Adventures of Captain Hatteras — CHAPTER IX'),
    (513, 'ACH-ch42', 'The Adventures of Captain Hatteras — CHAPTER X'),
    (514, 'ACH-ch43', 'The Adventures of Captain Hatteras — CHAPTER XI'),
    (515, 'ACH-ch44', 'The Adventures of Captain Hatteras — CHAPTER XII'),
    (516, 'ACH-ch45', 'The Adventures of Captain Hatteras — CHAPTER XIII'),
    (517, 'ACH-ch46', 'The Adventures of Captain Hatteras — CHAPTER XIV'),
    (518, 'ACH-ch47', 'The Adventures of Captain Hatteras — CHAPTER XV'),
    (519, 'ACH-ch48', 'The Adventures of Captain Hatteras — CHAPTER XVI'),
    (520, 'ACH-ch49', 'The Adventures of Captain Hatteras — CHAPTER XVII'),
    (521, 'ACH-ch50', 'The Adventures of Captain Hatteras — CHAPTER XVIII'),
    (522, 'ACH-ch51', 'The Adventures of Captain Hatteras — CHAPTER XIX'),
    (523, 'ACH-ch52', 'The Adventures of Captain Hatteras — CHAPTER XX'),
    (524, 'ACH-ch53', 'The Adventures of Captain Hatteras — CHAPTER XXI'),
    (525, 'ACH-ch54', 'The Adventures of Captain Hatteras — CHAPTER XXII'),
    (526, 'ACH-ch55', 'The Adventures of Captain Hatteras — CHAPTER XXIII'),
    (527, 'ACH-ch56', 'The Adventures of Captain Hatteras — CHAPTER XXIV'),
    (528, 'ACH-ch57', 'The Adventures of Captain Hatteras — CHAPTER XXV'),
    (529, 'ACH-ch58', 'The Adventures of Captain Hatteras — CHAPTER XXVI'),
    (530, 'SC-ch01', 'In Search of the Castaways — CHAPTER I THE SHARK'),
    (531, 'SC-ch02', 'In Search of the Castaways — CHAPTER II THE THREE DOCUMENTS'),
    (532, 'SC-ch03', "In Search of the Castaways — CHAPTER III THE CAPTAIN'S CHILDREN"),
    (533, 'SC-ch04', "In Search of the Castaways — CHAPTER IV LADY GLENARVAN'S PROPOSAL"),
    (534, 'SC-ch05', 'In Search of the Castaways — CHAPTER V THE DEPARTURE OF THE “DUNCAN”'),
    (535, 'SC-ch06', 'In Search of the Castaways — CHAPTER VI AN UNEXPECTED PASSENGER'),
    (536, 'SC-ch07', 'In Search of the Castaways — CHAPTER VII JACQUES PAGANEL IS UNDECEIVED'),
    (537, 'SC-ch08', "In Search of the Castaways — CHAPTER VIII THE GEOGRAPHER'S RESOLUTION"),
    (538, 'SC-ch09', 'In Search of the Castaways — CHAPTER IX THROUGH THE STRAITS OF MAGELLAN'),
    (539, 'SC-ch10', 'In Search of the Castaways — CHAPTER X THE COURSE DECIDED'),
    (540, 'SC-ch11', 'In Search of the Castaways — CHAPTER XI TRAVELING IN CHILI'),
    (541, 'SC-ch12', 'In Search of the Castaways — CHAPTER XII ELEVEN THOUSAND FEET ALOFT'),
    (542, 'SC-ch13', 'In Search of the Castaways — CHAPTER XIII A SUDDEN DESCENT'),
    (543, 'SC-ch14', 'In Search of the Castaways — CHAPTER XIV PROVIDENTIALLY RESCUED'),
    (544, 'SC-ch15', 'In Search of the Castaways — CHAPTER XV THALCAVE'),
    (545, 'SC-ch16', 'In Search of the Castaways — CHAPTER XVI THE NEWS OF THE LOST CAPTAIN'),
    (546, 'SC-ch17', 'In Search of the Castaways — CHAPTER XVII A SERIOUS NECESSITY'),
    (547, 'SC-ch18', 'In Search of the Castaways — CHAPTER XVIII IN SEARCH OF WATER'),
    (548, 'SC-ch19', 'In Search of the Castaways — CHAPTER XIX THE RED WOLVES'),
    (549, 'SC-ch20', 'In Search of the Castaways — CHAPTER XX STRANGE SIGNS'),
    (550, 'SC-ch21', 'In Search of the Castaways — CHAPTER XXI A FALSE TRAIL'),
    (551, 'SC-ch22', 'In Search of the Castaways — CHAPTER XXII THE FLOOD'),
    (552, 'SC-ch23', 'In Search of the Castaways — CHAPTER XXIII A SINGULAR ABODE'),
    (553, 'SC-ch24', "In Search of the Castaways — CHAPTER XXIV PAGANEL'S DISCLOSURE"),
    (554, 'SC-ch25', 'In Search of the Castaways — CHAPTER XXV BETWEEN FIRE AND WATER'),
    (555, 'SC-ch26', 'In Search of the Castaways — CHAPTER XXVI THE RETURN ON BOARD'),
    (556, 'SC-ch27', 'In Search of the Castaways — CHAPTER I A NEW DESTINATION'),
    (557, 'SC-ch28', "In Search of the Castaways — CHAPTER II TRISTAN D'ACUNHA AND THE ISLE OF AMSTERDAM"),
    (558, 'SC-ch29', 'In Search of the Castaways — CHAPTER III CAPE TOWN AND M. VIOT'),
    (559, 'SC-ch30', 'In Search of the Castaways — CHAPTER IV A WAGER AND HOW DECIDED'),
    (560, 'SC-ch31', 'In Search of the Castaways — CHAPTER V THE STORM ON THE INDIAN OCEAN'),
    (561, 'SC-ch32', 'In Search of the Castaways — CHAPTER VI A HOSPITABLE COLONIST'),
    (562, 'SC-ch33', 'In Search of the Castaways — CHAPTER VII THE QUARTERMASTER OF THE “BRITANNIA”'),
    (563, 'SC-ch34', 'In Search of the Castaways — CHAPTER VIII PREPARATION FOR THE JOURNEY'),
    (564, 'SC-ch35', 'In Search of the Castaways — CHAPTER IX A COUNTRY OF PARADOXES'),
    (565, 'SC-ch36', 'In Search of the Castaways — CHAPTER X AN ACCIDENT'),
    (566, 'SC-ch37', 'In Search of the Castaways — CHAPTER XI CRIME OR CALAMITY'),
    (567, 'SC-ch38', 'In Search of the Castaways — CHAPTER XII TOLINE OF THE LACHLAN'),
    (568, 'SC-ch39', 'In Search of the Castaways — CHAPTER XIII A WARNING'),
    (569, 'SC-ch40', 'In Search of the Castaways — CHAPTER XIV WEALTH IN THE WILDERNESS'),
    (570, 'SC-ch41', 'In Search of the Castaways — CHAPTER XV SUSPICIOUS OCCURRENCES'),
    (571, 'SC-ch42', 'In Search of the Castaways — CHAPTER XVI A STARTLING DISCOVERY'),
    (572, 'SC-ch43', 'In Search of the Castaways — CHAPTER XVII THE PLOT UNVEILED'),
    (573, 'SC-ch44', 'In Search of the Castaways — CHAPTER XVIII FOUR DAYS OF ANGUISH'),
    (574, 'SC-ch45', 'In Search of the Castaways — CHAPTER XIX HELPLESS AND HOPELESS'),
    (575, 'SC-ch46', 'In Search of the Castaways — CHAPTER I A ROUGH CAPTAIN'),
    (576, 'SC-ch47', 'In Search of the Castaways — CHAPTER II NAVIGATORS AND THEIR DISCOVERIES'),
    (577, 'SC-ch48', 'In Search of the Castaways — CHAPTER III THE MARTYR-ROLL OF NAVIGATORS'),
    (578, 'SC-ch49', 'In Search of the Castaways — CHAPTER IV THE WRECK OF THE “MACQUARIE”'),
    (579, 'SC-ch50', 'In Search of the Castaways — CHAPTER V CANNIBALS'),
    (580, 'SC-ch51', 'In Search of the Castaways — CHAPTER VI A DREADED COUNTRY'),
    (581, 'SC-ch52', 'In Search of the Castaways — CHAPTER VII THE MAORI WAR'),
    (582, 'SC-ch53', 'In Search of the Castaways — CHAPTER VIII ON THE ROAD TO AUCKLAND'),
    (583, 'SC-ch54', 'In Search of the Castaways — CHAPTER IX INTRODUCTION TO THE CANNIBALS'),
    (584, 'SC-ch55', 'In Search of the Castaways — CHAPTER X A MOMENTOUS INTERVIEW'),
    (585, 'SC-ch56', "In Search of the Castaways — CHAPTER XI THE CHIEF'S FUNERAL"),
    (586, 'SC-ch57', 'In Search of the Castaways — CHAPTER XII STRANGELY LIBERATED'),
    (587, 'SC-ch58', 'In Search of the Castaways — CHAPTER XIII THE SACRED MOUNTAIN'),
    (588, 'SC-ch59', 'In Search of the Castaways — CHAPTER XIV A BOLD STRATAGEM'),
    (589, 'SC-ch60', 'In Search of the Castaways — CHAPTER XV FROM PERIL TO SAFETY'),
    (590, 'SC-ch61', 'In Search of the Castaways — CHAPTER XVI WHY THE “DUNCAN” WENT TO NEW ZEALAND'),
    (591, 'SC-ch62', "In Search of the Castaways — CHAPTER XVII AYRTON'S OBSTINACY"),
    (592, 'SC-ch63', 'In Search of the Castaways — CHAPTER XVIII A DISCOURAGING CONFESSION'),
    (593, 'SC-ch64', 'In Search of the Castaways — CHAPTER XIX A CRY IN THE NIGHT'),
    (594, 'SC-ch65', "In Search of the Castaways — CHAPTER XX CAPTAIN GRANT'S STORY"),
    (595, 'SC-ch66', "In Search of the Castaways — CHAPTER XXI PAGANEL'S LAST ENTANGLEMENT"),
    (596, 'MS-ch01', 'Michael Strogoff — BOOK I'),
    (597, 'MS-ch02', 'Michael Strogoff — CHAPTER I A FETE AT THE NEW PALACE'),
    (598, 'MS-ch03', 'Michael Strogoff — CHAPTER II RUSSIANS AND TARTARS'),
    (599, 'MS-ch04', 'Michael Strogoff — CHAPTER III MICHAEL STROGOFF MEETS THE CZAR'),
    (600, 'MS-ch05', 'Michael Strogoff — CHAPTER IV FROM MOSCOW TO NIJNI-NOVGOROD'),
    (601, 'MS-ch06', 'Michael Strogoff — CHAPTER V THE TWO ANNOUNCEMENTS'),
    (602, 'MS-ch07', 'Michael Strogoff — CHAPTER VI BROTHER AND SISTER'),
    (603, 'MS-ch08', 'Michael Strogoff — CHAPTER VII GOING DOWN THE VOLGA'),
    (604, 'MS-ch09', 'Michael Strogoff — CHAPTER VIII GOING UP THE KAMA'),
    (605, 'MS-ch10', 'Michael Strogoff — CHAPTER IX DAY AND NIGHT IN A TARANTASS'),
    (606, 'MS-ch11', 'Michael Strogoff — CHAPTER X A STORM IN THE URAL MOUNTAINS'),
    (607, 'MS-ch12', 'Michael Strogoff — CHAPTER XI TRAVELERS IN DISTRESS'),
    (608, 'MS-ch13', 'Michael Strogoff — CHAPTER XII PROVOCATION'),
    (609, 'MS-ch14', 'Michael Strogoff — CHAPTER XIII DUTY BEFORE EVERYTHING'),
    (610, 'MS-ch15', 'Michael Strogoff — CHAPTER XIV MOTHER AND SON'),
    (611, 'MS-ch16', 'Michael Strogoff — CHAPTER XV THE MARSHES OF THE BARABA'),
    (612, 'MS-ch17', 'Michael Strogoff — CHAPTER XVI A FINAL EFFORT'),
    (613, 'MS-ch18', 'Michael Strogoff — CHAPTER XVII THE RIVALS'),
    (614, 'MS-ch19', 'Michael Strogoff — BOOK II'),
    (615, 'MS-ch20', 'Michael Strogoff — CHAPTER I A TARTAR CAMP'),
    (616, 'MS-ch21', 'Michael Strogoff — CHAPTER II CORRESPONDENTS IN TROUBLE'),
    (617, 'MS-ch22', 'Michael Strogoff — CHAPTER III BLOW FOR BLOW'),
    (618, 'MS-ch23', 'Michael Strogoff — CHAPTER IV THE TRIUMPHAL ENTRY'),
    (619, 'MS-ch24', 'Michael Strogoff — CHAPTER V “LOOK WHILE YOU MAY!”'),
    (620, 'MS-ch25', 'Michael Strogoff — CHAPTER VI A FRIEND ON THE HIGHWAY'),
    (621, 'MS-ch26', 'Michael Strogoff — CHAPTER VII THE PASSAGE OF THE YENISEI'),
    (622, 'MS-ch27', 'Michael Strogoff — CHAPTER VIII A HARE CROSSES THE ROAD'),
    (623, 'MS-ch28', 'Michael Strogoff — CHAPTER IX IN THE STEPPE'),
    (624, 'MS-ch29', 'Michael Strogoff — CHAPTER X BAIKAL AND ANGARA'),
    (625, 'MS-ch30', 'Michael Strogoff — CHAPTER XI BETWEEN TWO BANKS'),
    (626, 'MS-ch31', 'Michael Strogoff — CHAPTER XII IRKUTSK'),
    (627, 'MS-ch32', "Michael Strogoff — CHAPTER XIII THE CZAR'S COURIER"),
    (628, 'MS-ch33', 'Michael Strogoff — CHAPTER XIV THE NIGHT OF THE FIFTH OF OCTOBER'),
    (629, 'MS-ch34', 'Michael Strogoff — CHAPTER XV CONCLUSION'),
    (630, 'OC-ch01', 'Off on a Comet — BOOK I'),
    (631, 'OC-ch02', 'Off on a Comet — CHAPTER I. A CHALLENGE'),
    (632, 'OC-ch03', 'Off on a Comet — CHAPTER II. CAPTAIN SERVADAC AND HIS ORDERLY'),
    (633, 'OC-ch04', 'Off on a Comet — CHAPTER III. INTERRUPTED EFFUSIONS'),
    (634, 'OC-ch05', 'Off on a Comet — CHAPTER IV. A CONVULSION OF NATURE'),
    (635, 'OC-ch06', 'Off on a Comet — CHAPTER V. A MYSTERIOUS SEA'),
    (636, 'OC-ch07', 'Off on a Comet — CHAPTER VI. THE CAPTAIN MAKES AN EXPLORATION'),
    (637, 'OC-ch08', 'Off on a Comet — CHAPTER VII. BEN ZOOF WATCHES IN VAIN'),
    (638, 'OC-ch09', 'Off on a Comet — CHAPTER VIII. VENUS IN PERILOUS PROXIMITY'),
    (639, 'OC-ch10', 'Off on a Comet — CHAPTER IX. INQUIRIES UNSATISFIED'),
    (640, 'OC-ch11', 'Off on a Comet — CHAPTER X. A SEARCH FOR ALGERIA'),
    (641, 'OC-ch12', 'Off on a Comet — CHAPTER XI. AN ISLAND TOMB'),
    (642, 'OC-ch13', 'Off on a Comet — CHAPTER XII. AT THE MERCY OF THE WINDS'),
    (643, 'OC-ch14', 'Off on a Comet — CHAPTER XIII. A ROYAL SALUTE'),
    (644, 'OC-ch15', 'Off on a Comet — CHAPTER XIV. SENSITIVE NATIONALITY'),
    (645, 'OC-ch16', 'Off on a Comet — CHAPTER XV. AN ENIGMA FROM THE SEA'),
    (646, 'OC-ch17', 'Off on a Comet — CHAPTER XVI. THE RESIDUUM OF A CONTINENT'),
    (647, 'OC-ch18', 'Off on a Comet — CHAPTER XVII. A SECOND ENIGMA'),
    (648, 'OC-ch19', 'Off on a Comet — CHAPTER XVIII. AN UNEXPECTED POPULATION'),
    (649, 'OC-ch20', "Off on a Comet — CHAPTER XIX. GALLIA'S GOVERNOR GENERAL"),
    (650, 'OC-ch21', 'Off on a Comet — CHAPTER XX. A LIGHT ON THE HORIZON'),
    (651, 'OC-ch22', 'Off on a Comet — CHAPTER XXI. WINTER QUARTERS'),
    (652, 'OC-ch23', 'Off on a Comet — CHAPTER XXII. A FROZEN OCEAN'),
    (653, 'OC-ch24', 'Off on a Comet — CHAPTER XXIII. A CARRIER-PIGEON'),
    (654, 'OC-ch25', 'Off on a Comet — CHAPTER XXIV. A SLEDGE-RIDE'),
    (655, 'OC-ch26', 'Off on a Comet — BOOK II'),
    (656, 'OC-ch27', 'Off on a Comet — CHAPTER I. THE ASTRONOMER'),
    (657, 'OC-ch28', 'Off on a Comet — CHAPTER II. A REVELATION'),
    (658, 'OC-ch29', "Off on a Comet — CHAPTER III. THE PROFESSOR'S EXPERIENCES"),
    (659, 'OC-ch30', 'Off on a Comet — CHAPTER IV. A REVISED CALENDAR'),
    (660, 'OC-ch31', 'Off on a Comet — CHAPTER V. WANTED: A STEELYARD'),
    (661, 'OC-ch32', 'Off on a Comet — CHAPTER VI. MONEY AT A PREMIUM'),
    (662, 'OC-ch33', 'Off on a Comet — CHAPTER VII. GALLIA WEIGHED'),
    (663, 'OC-ch34', 'Off on a Comet — CHAPTER VIII. JUPITER SOMEWHAT CLOSE'),
    (664, 'OC-ch35', 'Off on a Comet — CHAPTER IX MARKET PRICES IN GALLIA'),
    (665, 'OC-ch36', 'Off on a Comet — CHAPTER X. FAR INTO SPACE'),
    (666, 'OC-ch37', 'Off on a Comet — CHAPTER XI. A FETE DAY'),
    (667, 'OC-ch38', 'Off on a Comet — CHAPTER XII. THE BOWELS OF THE COMET'),
    (668, 'OC-ch39', 'Off on a Comet — CHAPTER XIII. DREARY MONTHS'),
    (669, 'OC-ch40', 'Off on a Comet — CHAPTER XIV. THE PROFESSOR PERPLEXED'),
    (670, 'OC-ch41', 'Off on a Comet — CHAPTER XV. A JOURNEY AND A DISAPPOINTMENT'),
    (671, 'OC-ch42', 'Off on a Comet — CHAPTER XVI. A BOLD PROPOSITION'),
    (672, 'OC-ch43', 'Off on a Comet — CHAPTER XVII. THE VENTURE MADE'),
    (673, 'OC-ch44', 'Off on a Comet — CHAPTER XVIII. SUSPENSE'),
    (674, 'OC-ch45', 'Off on a Comet — CHAPTER XIX. BACK AGAIN'),
    (675, 'RC-ch01', 'Robur the Conqueror — CHAPTER I'),
    (676, 'RC-ch02', 'Robur the Conqueror — CHAPTER II'),
    (677, 'RC-ch03', 'Robur the Conqueror — CHAPTER III'),
    (678, 'RC-ch04', 'Robur the Conqueror — CHAPTER IV'),
    (679, 'RC-ch05', 'Robur the Conqueror — CHAPTER V'),
    (680, 'RC-ch06', 'Robur the Conqueror — CHAPTER VI'),
    (681, 'RC-ch07', 'Robur the Conqueror — CHAPTER VII'),
    (682, 'RC-ch08', 'Robur the Conqueror — CHAPTER VIII'),
    (683, 'RC-ch09', 'Robur the Conqueror — CHAPTER IX'),
    (684, 'RC-ch10', 'Robur the Conqueror — CHAPTER X'),
    (685, 'RC-ch11', 'Robur the Conqueror — CHAPTER XI'),
    (686, 'RC-ch12', 'Robur the Conqueror — CHAPTER XII'),
    (687, 'RC-ch13', 'Robur the Conqueror — CHAPTER XIII'),
    (688, 'RC-ch14', 'Robur the Conqueror — CHAPTER XIV'),
    (689, 'RC-ch15', 'Robur the Conqueror — CHAPTER XV'),
    (690, 'RC-ch16', 'Robur the Conqueror — CHAPTER XVI'),
    (691, 'RC-ch17', 'Robur the Conqueror — CHAPTER XVII'),
    (692, 'RC-ch18', 'Robur the Conqueror — CHAPTER XVIII'),
    (693, 'RC-ch19', 'Robur the Conqueror — CHAPTER XIX'),
    (694, 'RC-ch20', 'Robur the Conqueror — CHAPTER XX'),
    (695, 'RC-ch21', 'Robur the Conqueror — CHAPTER XXI'),
    (696, 'RC-ch22', 'Robur the Conqueror — CHAPTER XXII'),
    (697, 'RC-ch23', 'Robur the Conqueror — CHAPTER XXIII'),
    (698, 'ASC-ch01', 'The Adventures of a Special Correspondent — CHAPTER I'),
    (699, 'ASC-ch02', 'The Adventures of a Special Correspondent — CHAPTER II'),
    (700, 'ASC-ch03', 'The Adventures of a Special Correspondent — CHAPTER III'),
    (701, 'ASC-ch04', 'The Adventures of a Special Correspondent — CHAPTER IV'),
    (702, 'ASC-ch05', 'The Adventures of a Special Correspondent — CHAPTER V'),
    (703, 'ASC-ch06', 'The Adventures of a Special Correspondent — CHAPTER VI'),
    (704, 'ASC-ch07', 'The Adventures of a Special Correspondent — CHAPTER VII'),
    (705, 'ASC-ch08', 'The Adventures of a Special Correspondent — CHAPTER VIII'),
    (706, 'ASC-ch09', 'The Adventures of a Special Correspondent — CHAPTER IX'),
    (707, 'ASC-ch10', 'The Adventures of a Special Correspondent — CHAPTER X'),
    (708, 'ASC-ch11', 'The Adventures of a Special Correspondent — CHAPTER XI'),
    (709, 'ASC-ch12', 'The Adventures of a Special Correspondent — CHAPTER XII'),
    (710, 'ASC-ch13', 'The Adventures of a Special Correspondent — CHAPTER XIII'),
    (711, 'ASC-ch14', 'The Adventures of a Special Correspondent — CHAPTER XIV'),
    (712, 'ASC-ch15', 'The Adventures of a Special Correspondent — CHAPTER XV'),
    (713, 'ASC-ch16', 'The Adventures of a Special Correspondent — CHAPTER XVI'),
    (714, 'ASC-ch17', 'The Adventures of a Special Correspondent — CHAPTER XVII'),
    (715, 'ASC-ch18', 'The Adventures of a Special Correspondent — CHAPTER XVIII'),
    (716, 'ASC-ch19', 'The Adventures of a Special Correspondent — CHAPTER XIX'),
    (717, 'ASC-ch20', 'The Adventures of a Special Correspondent — CHAPTER XX'),
    (718, 'ASC-ch21', 'The Adventures of a Special Correspondent — CHAPTER XXI'),
    (719, 'ASC-ch22', 'The Adventures of a Special Correspondent — CHAPTER XXII'),
    (720, 'ASC-ch23', 'The Adventures of a Special Correspondent — CHAPTER XXIII'),
    (721, 'ASC-ch24', 'The Adventures of a Special Correspondent — CHAPTER XXIV'),
    (722, 'ASC-ch25', 'The Adventures of a Special Correspondent — CHAPTER XXV'),
    (723, 'ASC-ch26', 'The Adventures of a Special Correspondent — CHAPTER XXVI'),
    (724, 'ASC-ch27', 'The Adventures of a Special Correspondent — CHAPTER XXVII'),
    (725, 'BR-ch01', 'The Blockade Runners — CHAPTER I'),
    (726, 'BR-ch02', 'The Blockade Runners — CHAPTER II'),
    (727, 'BR-ch03', 'The Blockade Runners — CHAPTER III'),
    (728, 'BR-ch04', 'The Blockade Runners — CHAPTER IV'),
    (729, 'BR-ch05', 'The Blockade Runners — CHAPTER V'),
    (730, 'BR-ch06', 'The Blockade Runners — CHAPTER VI'),
    (731, 'BR-ch07', 'The Blockade Runners — CHAPTER VII'),
    (732, 'BR-ch08', 'The Blockade Runners — CHAPTER VIII'),
    (733, 'BR-ch09', 'The Blockade Runners — CHAPTER IX'),
    (734, 'BR-ch10', 'The Blockade Runners — CHAPTER X'),
    (735, 'FC-ch01', 'The Fur Country — CHAPTER I'),
    (736, 'FC-ch02', 'The Fur Country — CHAPTER II'),
    (737, 'FC-ch03', 'The Fur Country — CHAPTER III'),
    (738, 'FC-ch04', 'The Fur Country — CHAPTER IV'),
    (739, 'FC-ch05', 'The Fur Country — CHAPTER V'),
    (740, 'FC-ch06', 'The Fur Country — CHAPTER VI'),
    (741, 'FC-ch07', 'The Fur Country — CHAPTER VII'),
    (742, 'FC-ch08', 'The Fur Country — CHAPTER VIII'),
    (743, 'FC-ch09', 'The Fur Country — CHAPTER IX'),
    (744, 'FC-ch10', 'The Fur Country — CHAPTER X'),
    (745, 'FC-ch11', 'The Fur Country — CHAPTER XI'),
    (746, 'FC-ch12', 'The Fur Country — CHAPTER XII'),
    (747, 'FC-ch13', 'The Fur Country — CHAPTER XIII'),
    (748, 'FC-ch14', 'The Fur Country — CHAPTER XIV'),
    (749, 'FC-ch15', 'The Fur Country — CHAPTER XV'),
    (750, 'FC-ch16', 'The Fur Country — CHAPTER XVI'),
    (751, 'FC-ch17', 'The Fur Country — CHAPTER XVII'),
    (752, 'FC-ch18', 'The Fur Country — CHAPTER XVIII'),
    (753, 'FC-ch19', 'The Fur Country — CHAPTER XIX'),
    (754, 'FC-ch20', 'The Fur Country — CHAPTER XX'),
    (755, 'FC-ch21', 'The Fur Country — CHAPTER XXI'),
    (756, 'FC-ch22', 'The Fur Country — CHAPTER XXII'),
    (757, 'FC-ch23', 'The Fur Country — CHAPTER XXIII'),
    (758, 'FC-ch24', 'The Fur Country — CHAPTER I'),
    (759, 'FC-ch25', 'The Fur Country — CHAPTER II'),
    (760, 'FC-ch26', 'The Fur Country — CHAPTER III'),
    (761, 'FC-ch27', 'The Fur Country — CHAPTER IV'),
    (762, 'FC-ch28', 'The Fur Country — CHAPTER V'),
    (763, 'FC-ch29', 'The Fur Country — CHAPTER VI'),
    (764, 'FC-ch30', 'The Fur Country — CHAPTER VII'),
    (765, 'FC-ch31', 'The Fur Country — CHAPTER VIII'),
    (766, 'FC-ch32', 'The Fur Country — CHAPTER IX'),
    (767, 'FC-ch33', 'The Fur Country — CHAPTER X'),
    (768, 'FC-ch34', 'The Fur Country — CHAPTER XI'),
    (769, 'FC-ch35', 'The Fur Country — CHAPTER XII'),
    (770, 'FC-ch36', 'The Fur Country — CHAPTER XIII'),
    (771, 'FC-ch37', 'The Fur Country — CHAPTER XIV'),
    (772, 'FC-ch38', 'The Fur Country — CHAPTER XV'),
    (773, 'FC-ch39', 'The Fur Country — CHAPTER XVI'),
    (774, 'FC-ch40', 'The Fur Country — CHAPTER XVII'),
    (775, 'FC-ch41', 'The Fur Country — CHAPTER XVIII'),
    (776, 'FC-ch42', 'The Fur Country — CHAPTER XIX'),
    (777, 'FC-ch43', 'The Fur Country — CHAPTER XX'),
    (778, 'FC-ch44', 'The Fur Country — CHAPTER XXI'),
    (779, 'FC-ch45', 'The Fur Country — CHAPTER XXII'),
    (780, 'FC-ch46', 'The Fur Country — CHAPTER XXIII'),
    (781, 'FC-ch47', 'The Fur Country — CHAPTER XXIV'),
    (782, 'MW-ch01', 'The Master of the World — CHAPTER 1'),
    (783, 'MW-ch02', 'The Master of the World — CHAPTER 2'),
    (784, 'MW-ch03', 'The Master of the World — CHAPTER 3'),
    (785, 'MW-ch04', 'The Master of the World — CHAPTER 4'),
    (786, 'MW-ch05', 'The Master of the World — CHAPTER 5'),
    (787, 'MW-ch06', 'The Master of the World — CHAPTER 6'),
    (788, 'MW-ch07', 'The Master of the World — CHAPTER 7'),
    (789, 'MW-ch08', 'The Master of the World — CHAPTER 8'),
    (790, 'MW-ch09', 'The Master of the World — CHAPTER 9'),
    (791, 'MW-ch10', 'The Master of the World — CHAPTER 10'),
    (792, 'MW-ch11', 'The Master of the World — CHAPTER 11'),
    (793, 'MW-ch12', 'The Master of the World — CHAPTER 12'),
    (794, 'MW-ch13', 'The Master of the World — CHAPTER 13'),
    (795, 'MW-ch14', 'The Master of the World — CHAPTER 14'),
    (796, 'MW-ch15', 'The Master of the World — CHAPTER 15'),
    (797, 'MW-ch16', 'The Master of the World — CHAPTER 16'),
    (798, 'MW-ch17', 'The Master of the World — CHAPTER 17'),
    (799, 'MW-ch18', 'The Master of the World — CHAPTER 18'),
    (800, 'PL-ch01', 'The Pearl of Lima — CHAPTER I'),
    (801, 'PL-ch02', 'The Pearl of Lima — CHAPTER II'),
    (802, 'PL-ch03', 'The Pearl of Lima — CHAPTER III'),
    (803, 'PL-ch04', 'The Pearl of Lima — CHAPTER IV'),
    (804, 'PL-ch05', 'The Pearl of Lima — CHAPTER V'),
    (805, 'PL-ch06', 'The Pearl of Lima — CHAPTER VI'),
    (806, 'PL-ch07', 'The Pearl of Lima — CHAPTER VII'),
    (807, 'PL-ch08', 'The Pearl of Lima — CHAPTER VIII'),
    (808, 'PL-ch09', 'The Pearl of Lima — CHAPTER IX'),
    (809, 'SI-ch01', 'The Secret of the Island — CHAPTER ONE'),
    (810, 'SI-ch02', 'The Secret of the Island — CHAPTER TWO'),
    (811, 'SI-ch03', 'The Secret of the Island — CHAPTER THREE'),
    (812, 'SI-ch04', 'The Secret of the Island — CHAPTER FOUR'),
    (813, 'SI-ch05', 'The Secret of the Island — CHAPTER FIVE'),
    (814, 'SI-ch06', 'The Secret of the Island — CHAPTER SIX'),
    (815, 'SI-ch07', 'The Secret of the Island — CHAPTER SEVEN'),
    (816, 'SI-ch08', 'The Secret of the Island — CHAPTER EIGHT'),
    (817, 'SI-ch09', 'The Secret of the Island — CHAPTER NINE'),
    (818, 'SI-ch10', 'The Secret of the Island — CHAPTER TEN'),
    (819, 'SI-ch11', 'The Secret of the Island — CHAPTER ELEVEN'),
    (820, 'SI-ch12', 'The Secret of the Island — CHAPTER TWELVE'),
    (821, 'SI-ch13', 'The Secret of the Island — CHAPTER THIRTEEN'),
    (822, 'SI-ch14', 'The Secret of the Island — CHAPTER FOURTEEN'),
    (823, 'SI-ch15', 'The Secret of the Island — CHAPTER FIFTEEN'),
    (824, 'SI-ch16', 'The Secret of the Island — CHAPTER SIXTEEN'),
    (825, 'SI-ch17', 'The Secret of the Island — CHAPTER SEVENTEEN'),
    (826, 'SI-ch18', 'The Secret of the Island — CHAPTER EIGHTEEN'),
    (827, 'SI-ch19', 'The Secret of the Island — CHAPTER NINETEEN'),
    (828, 'SI-ch20', 'The Secret of the Island — CHAPTER TWENTY'),
    (829, 'SC2-ch01', 'The Survivors of the Chancellor — CHAPTER I'),
    (830, 'SC2-ch02', 'The Survivors of the Chancellor — CHAPTER II'),
    (831, 'SC2-ch03', 'The Survivors of the Chancellor — CHAPTER III'),
    (832, 'SC2-ch04', 'The Survivors of the Chancellor — CHAPTER IV'),
    (833, 'SC2-ch05', 'The Survivors of the Chancellor — CHAPTER V'),
    (834, 'SC2-ch06', 'The Survivors of the Chancellor — CHAPTER VI'),
    (835, 'SC2-ch07', 'The Survivors of the Chancellor — CHAPTER VII'),
    (836, 'SC2-ch08', 'The Survivors of the Chancellor — CHAPTER VIII'),
    (837, 'SC2-ch09', 'The Survivors of the Chancellor — CHAPTER IX'),
    (838, 'SC2-ch10', 'The Survivors of the Chancellor — CHAPTER X'),
    (839, 'SC2-ch11', 'The Survivors of the Chancellor — CHAPTER XI'),
    (840, 'SC2-ch12', 'The Survivors of the Chancellor — CHAPTER XII'),
    (841, 'SC2-ch13', 'The Survivors of the Chancellor — CHAPTER XIII'),
    (842, 'SC2-ch14', 'The Survivors of the Chancellor — CHAPTER XIV'),
    (843, 'SC2-ch15', 'The Survivors of the Chancellor — CHAPTER XV'),
    (844, 'SC2-ch16', 'The Survivors of the Chancellor — CHAPTER XVI'),
    (845, 'SC2-ch17', 'The Survivors of the Chancellor — CHAPTER XVII'),
    (846, 'SC2-ch18', 'The Survivors of the Chancellor — CHAPTER XVIII'),
    (847, 'SC2-ch19', 'The Survivors of the Chancellor — CHAPTER XIX'),
    (848, 'SC2-ch20', 'The Survivors of the Chancellor — CHAPTER XX'),
    (849, 'SC2-ch21', 'The Survivors of the Chancellor — CHAPTER XXI'),
    (850, 'SC2-ch22', 'The Survivors of the Chancellor — CHAPTER XXII'),
    (851, 'SC2-ch23', 'The Survivors of the Chancellor — CHAPTER XXIII'),
    (852, 'SC2-ch24', 'The Survivors of the Chancellor — CHAPTER XXIV'),
    (853, 'SC2-ch25', 'The Survivors of the Chancellor — CHAPTER XXV'),
    (854, 'SC2-ch26', 'The Survivors of the Chancellor — CHAPTER XXVI'),
    (855, 'SC2-ch27', 'The Survivors of the Chancellor — CHAPTER XXVII'),
    (856, 'SC2-ch28', 'The Survivors of the Chancellor — CHAPTER XXVIII'),
    (857, 'SC2-ch29', 'The Survivors of the Chancellor — CHAPTER XXIX'),
    (858, 'SC2-ch30', 'The Survivors of the Chancellor — CHAPTER XXX'),
    (859, 'SC2-ch31', 'The Survivors of the Chancellor — CHAPTER XXXI'),
    (860, 'SC2-ch32', 'The Survivors of the Chancellor — CHAPTER XXXII'),
    (861, 'SC2-ch33', 'The Survivors of the Chancellor — CHAPTER XXXIII'),
    (862, 'SC2-ch34', 'The Survivors of the Chancellor — CHAPTER XXXIV'),
    (863, 'SC2-ch35', 'The Survivors of the Chancellor — CHAPTER XXXV'),
    (864, 'SC2-ch36', 'The Survivors of the Chancellor — CHAPTER XXXVI'),
    (865, 'SC2-ch37', 'The Survivors of the Chancellor — CHAPTER XXXVII'),
    (866, 'SC2-ch38', 'The Survivors of the Chancellor — CHAPTER XXXVIII'),
    (867, 'SC2-ch39', 'The Survivors of the Chancellor — CHAPTER XXXIX'),
    (868, 'SC2-ch40', 'The Survivors of the Chancellor — CHAPTER XL'),
    (869, 'SC2-ch41', 'The Survivors of the Chancellor — CHAPTER XLI'),
    (870, 'SC2-ch42', 'The Survivors of the Chancellor — CHAPTER XLII'),
    (871, 'SC2-ch43', 'The Survivors of the Chancellor — CHAPTER XLIII'),
    (872, 'SC2-ch44', 'The Survivors of the Chancellor — CHAPTER XLIV'),
    (873, 'SC2-ch45', 'The Survivors of the Chancellor — CHAPTER XLV'),
    (874, 'SC2-ch46', 'The Survivors of the Chancellor — CHAPTER XLVI'),
    (875, 'SC2-ch47', 'The Survivors of the Chancellor — CHAPTER XLVII'),
    (876, 'SC2-ch48', 'The Survivors of the Chancellor — CHAPTER XLVIII'),
    (877, 'SC2-ch49', 'The Survivors of the Chancellor — CHAPTER XLIX'),
    (878, 'SC2-ch50', 'The Survivors of the Chancellor — CHAPTER L'),
    (879, 'SC2-ch51', 'The Survivors of the Chancellor — CHAPTER LI'),
    (880, 'SC2-ch52', 'The Survivors of the Chancellor — CHAPTER LII'),
    (881, 'SC2-ch53', 'The Survivors of the Chancellor — CHAPTER LIII'),
    (882, 'SC2-ch54', 'The Survivors of the Chancellor — CHAPTER LIV'),
    (883, 'SC2-ch55', 'The Survivors of the Chancellor — CHAPTER LV'),
    (884, 'SC2-ch56', 'The Survivors of the Chancellor — CHAPTER LVI'),
    (885, 'SC2-ch57', 'The Survivors of the Chancellor — CHAPTER LVII'),
    (886, 'UC-ch01', 'The Underground City — CHAPTER I. CONTRADICTORY LETTERS'),
    (887, 'UC-ch02', 'The Underground City — CHAPTER II. ON THE ROAD'),
    (888, 'UC-ch03', 'The Underground City — CHAPTER III. THE DOCHART PIT'),
    (889, 'UC-ch04', 'The Underground City — CHAPTER IV. THE FORD FAMILY'),
    (890, 'UC-ch05', 'The Underground City — CHAPTER V. SOME STRANGE PHENOMENA'),
    (891, 'UC-ch06', "The Underground City — CHAPTER VI. SIMON FORD'S EXPERIMENT"),
    (892, 'UC-ch07', 'The Underground City — CHAPTER VII. NEW ABERFOYLE'),
    (893, 'UC-ch08', 'The Underground City — CHAPTER VIII. EXPLORING'),
    (894, 'UC-ch09', 'The Underground City — CHAPTER IX. THE FIRE-MAIDENS'),
    (895, 'UC-ch10', 'The Underground City — CHAPTER X. COAL TOWN'),
    (896, 'UC-ch11', 'The Underground City — CHAPTER XI. HANGING BY A THREAD'),
    (897, 'UC-ch12', 'The Underground City — CHAPTER XII. NELL ADOPTED'),
    (898, 'UC-ch13', 'The Underground City — CHAPTER XIII. ON THE REVOLVING LADDER'),
    (899, 'UC-ch14', 'The Underground City — CHAPTER XIV. A SUNRISE'),
    (900, 'UC-ch15', 'The Underground City — CHAPTER XV. LOCH LOMOND AND LOCH KATRINE'),
    (901, 'UC-ch16', 'The Underground City — CHAPTER XVI. A FINAL THREAT'),
    (902, 'UC-ch17', 'The Underground City — CHAPTER XVII. THE “MONK”'),
    (903, 'UC-ch18', "The Underground City — CHAPTER XVIII. NELL'S WEDDING"),
    (904, 'UC-ch19', 'The Underground City — CHAPTER XIX. THE LEGEND OF OLD SILFAX'),
    (905, 'WC-ch01', 'The Waif of the Cynthia — CHAPTER I'),
    (906, 'WC-ch02', 'The Waif of the Cynthia — CHAPTER II'),
    (907, 'WC-ch03', 'The Waif of the Cynthia — CHAPTER III'),
    (908, 'WC-ch04', 'The Waif of the Cynthia — CHAPTER IV'),
    (909, 'WC-ch05', 'The Waif of the Cynthia — CHAPTER V'),
    (910, 'WC-ch06', 'The Waif of the Cynthia — CHAPTER VI'),
    (911, 'WC-ch07', 'The Waif of the Cynthia — CHAPTER VII'),
    (912, 'WC-ch08', 'The Waif of the Cynthia — CHAPTER VIII'),
    (913, 'WC-ch09', 'The Waif of the Cynthia — CHAPTER IX'),
    (914, 'WC-ch10', 'The Waif of the Cynthia — CHAPTER X'),
    (915, 'WC-ch11', 'The Waif of the Cynthia — CHAPTER XI'),
    (916, 'WC-ch12', 'The Waif of the Cynthia — CHAPTER XII'),
    (917, 'WC-ch13', 'The Waif of the Cynthia — CHAPTER XIII'),
    (918, 'WC-ch14', 'The Waif of the Cynthia — CHAPTER XIV'),
    (919, 'WC-ch15', 'The Waif of the Cynthia — CHAPTER XV'),
    (920, 'WC-ch16', 'The Waif of the Cynthia — CHAPTER XVI'),
    (921, 'WC-ch17', 'The Waif of the Cynthia — CHAPTER XVII'),
    (922, 'WC-ch18', 'The Waif of the Cynthia — CHAPTER XVIII'),
    (923, 'WC-ch19', 'The Waif of the Cynthia — CHAPTER XIX'),
    (924, 'WC-ch20', 'The Waif of the Cynthia — CHAPTER XX'),
    (925, 'WC-ch21', 'The Waif of the Cynthia — CHAPTER XXI'),
    (926, 'WC-ch22', 'The Waif of the Cynthia — CHAPTER XXII'),
    (927, 'TN-ch01', 'Ticket No. 9672 — CHAPTER I'),
    (928, 'TN-ch02', 'Ticket No. 9672 — CHAPTER II'),
    (929, 'TN-ch03', 'Ticket No. 9672 — CHAPTER III'),
    (930, 'TN-ch04', 'Ticket No. 9672 — CHAPTER IV'),
    (931, 'TN-ch05', 'Ticket No. 9672 — CHAPTER V'),
    (932, 'TN-ch06', 'Ticket No. 9672 — CHAPTER VI'),
    (933, 'TN-ch07', 'Ticket No. 9672 — CHAPTER VII'),
    (934, 'TN-ch08', 'Ticket No. 9672 — CHAPTER VIII'),
    (935, 'TN-ch09', 'Ticket No. 9672 — CHAPTER IX'),
    (936, 'TN-ch10', 'Ticket No. 9672 — CHAPTER X'),
    (937, 'TN-ch11', 'Ticket No. 9672 — CHAPTER XI'),
    (938, 'TN-ch12', 'Ticket No. 9672 — CHAPTER XII'),
    (939, 'TN-ch13', 'Ticket No. 9672 — CHAPTER XIII'),
    (940, 'TN-ch14', 'Ticket No. 9672 — CHAPTER XIV'),
    (941, 'TN-ch15', 'Ticket No. 9672 — CHAPTER XV'),
    (942, 'TN-ch16', 'Ticket No. 9672 — CHAPTER XVI'),
    (943, 'TN-ch17', 'Ticket No. 9672 — CHAPTER XVII'),
    (944, 'TN-ch18', 'Ticket No. 9672 — CHAPTER XVIII'),
    (945, 'TN-ch19', 'Ticket No. 9672 — CHAPTER XIX'),
    (946, 'TN-ch20', 'Ticket No. 9672 — CHAPTER XX'),
    (947, 'TT-ch01', 'Topsy Turvy — CHAPTER I'),
    (948, 'TT-ch02', 'Topsy Turvy — CHAPTER II'),
    (949, 'TT-ch03', 'Topsy Turvy — CHAPTER III'),
    (950, 'TT-ch04', 'Topsy Turvy — CHAPTER IV'),
    (951, 'TT-ch05', 'Topsy Turvy — CHAPTER V'),
    (952, 'TT-ch06', 'Topsy Turvy — CHAPTER VI'),
    (953, 'TT-ch07', 'Topsy Turvy — CHAPTER VII'),
    (954, 'TT-ch08', 'Topsy Turvy — CHAPTER VIII'),
    (955, 'TT-ch09', 'Topsy Turvy — CHAPTER IX'),
    (956, 'TT-ch10', 'Topsy Turvy — CHAPTER X'),
    (957, 'TT-ch11', 'Topsy Turvy — CHAPTER XI'),
    (958, 'TT-ch12', 'Topsy Turvy — CHAPTER XII'),
    (959, 'TT-ch13', 'Topsy Turvy — CHAPTER XIII'),
    (960, 'TT-ch14', 'Topsy Turvy — CHAPTER XIV'),
    (961, 'TT-ch15', 'Topsy Turvy — CHAPTER XV'),
    (962, 'TT-ch16', 'Topsy Turvy — CHAPTER XVI'),
    (963, 'TT-ch17', 'Topsy Turvy — CHAPTER XVII'),
    (964, 'TT-ch18', 'Topsy Turvy — CHAPTER XVIII'),
    (965, 'TT-ch19', 'Topsy Turvy — CHAPTER XIX'),
    (966, 'TT-ch20', 'Topsy Turvy — CHAPTER XX'),
    (967, 'TT-ch21', 'Topsy Turvy — CHAPTER XXI'),
    (968, 'YEAR', 'In the Year 2889'),
]

NON_CHAPTER_PAGES = {'About', 'TOC'}
